### ISSUE TITLE
Database setup

### ISSUE THREAD

**Issue by fayimora** [tuxdna/play-oauth2-server#1]
How do we setup the database to run this app? The README could do with that information. I'm currently unable to run the app. Can't connect to this db `db.default.url="jdbc:sqlite:db/oauth2server_dev_db.sqlite"`

**Comment by fayimora** [comment]
Ping @tuxdna

**Comment by tuxdna** [comment]
Please check docs/README.devel file. Yes, it would be good to update README too.

**Comment by tuxdna** [comment]
Updated project README.md in this commit: https://github.com/tuxdna/play-oauth2-server/commit/a0becd1345d99fdea05cce076bc000ecb41d3b45

**Comment by fayimora** [comment]
Thanks @tuxdna I setup the DB, ran the app and sent the first request using wget but didn't get a response

**Comment by tuxdna** [comment]
Start the server:

```
$ sbt "run 9002"
```

This will start the server at port 9002. Now goto http://localhost:9002/

For the first time, you would see a message: `Database 'default' needs evolution!`. Now click "Apply this script now!"

In a separate terminal, go to Sqlite3 console and run queries from `fixtures.sql`.

```
$  sqlite3 db/oauth2server_dev_db.sqlite
sqlite> .read docs/fixtures.sql
```

Now you should be able to access the server using user `user1` and password `password`.  I hope that fixes the issue.

These instructions are now updated on [DEVELOPMENT.md](https://github.com/tuxdna/play-oauth2-server/blob/master/DEVELOPMENT.md) file.
